// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: display_ball

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Clock
void ui_Clock_screen_init(void);
void ui_event_Clock(lv_event_t * e);
lv_obj_t * ui_Clock;
void ui_event_left_panel_1(lv_event_t * e);
lv_obj_t * ui_left_panel_1;
void ui_event_right_panel_1(lv_event_t * e);
lv_obj_t * ui_right_panel_1;
lv_obj_t * ui_clock_label;
lv_obj_t * ui_clock_seconds;

// SCREEN: ui_Demo
void ui_Demo_screen_init(void);
lv_obj_t * ui_Demo;
void ui_event_left_panel_2(lv_event_t * e);
lv_obj_t * ui_left_panel_2;
void ui_event_right_panel_2(lv_event_t * e);
lv_obj_t * ui_right_panel_2;
lv_obj_t * ui_Spinner1;

// SCREEN: ui_Demo1
void ui_Demo1_screen_init(void);
lv_obj_t * ui_Demo1;
void ui_event_left_panel_3(lv_event_t * e);
lv_obj_t * ui_left_panel_3;
void ui_event_right_panel_3(lv_event_t * e);
lv_obj_t * ui_right_panel_3;
lv_obj_t * ui_Colorwheel1;

// SCREEN: ui_Demo2
void ui_Demo2_screen_init(void);
lv_obj_t * ui_Demo2;
void ui_event_left_panel_4(lv_event_t * e);
lv_obj_t * ui_left_panel_4;
void ui_event_right_panel_4(lv_event_t * e);
lv_obj_t * ui_right_panel_4;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Chart2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Clock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        clock_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        clock_unloaded(e);
    }
}
void ui_event_left_panel_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Demo2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Demo2_screen_init);
    }
}
void ui_event_right_panel_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Demo, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Demo_screen_init);
    }
}
void ui_event_left_panel_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Clock_screen_init);
    }
}
void ui_event_right_panel_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Demo1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Demo1_screen_init);
    }
}
void ui_event_left_panel_3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Demo, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Demo_screen_init);
    }
}
void ui_event_right_panel_3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Demo2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Demo2_screen_init);
    }
}
void ui_event_left_panel_4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Demo1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Demo1_screen_init);
    }
}
void ui_event_right_panel_4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Clock, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Clock_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Clock_screen_init();
    ui_Demo_screen_init();
    ui_Demo1_screen_init();
    ui_Demo2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Clock);
}
