// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: display_ball

#include "../ui.h"

void ui_Clock_screen_init(void)
{
    ui_Clock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_left_panel_1 = lv_obj_create(ui_Clock);
    lv_obj_set_width(ui_left_panel_1, 20);
    lv_obj_set_height(ui_left_panel_1, 20);
    lv_obj_clear_flag(ui_left_panel_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_left_panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_left_panel_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_left_panel_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_right_panel_1 = lv_obj_create(ui_Clock);
    lv_obj_set_width(ui_right_panel_1, 20);
    lv_obj_set_height(ui_right_panel_1, 20);
    lv_obj_set_align(ui_right_panel_1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_right_panel_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_right_panel_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_right_panel_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_right_panel_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clock_label = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_clock_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clock_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clock_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clock_label, "12:00");
    lv_obj_set_style_text_font(ui_clock_label, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clock_seconds = lv_arc_create(ui_Clock);
    lv_obj_set_width(ui_clock_seconds, 240);
    lv_obj_set_height(ui_clock_seconds, 240);
    lv_obj_set_align(ui_clock_seconds, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clock_seconds, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_clock_seconds, 0, 60);
    lv_arc_set_value(ui_clock_seconds, 10);
    lv_arc_set_bg_angles(ui_clock_seconds, 0, 360);
    lv_arc_set_rotation(ui_clock_seconds, 270);
    lv_obj_set_style_arc_color(ui_clock_seconds, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clock_seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_clock_seconds, lv_color_hex(0x202020), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clock_seconds, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clock_seconds, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_clock_seconds, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_clock_seconds, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_clock_seconds, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_clock_seconds, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_clock_seconds, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_left_panel_1, ui_event_left_panel_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_right_panel_1, ui_event_right_panel_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Clock, ui_event_Clock, LV_EVENT_ALL, NULL);

}
