// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: display_ball

#include "../ui.h"

void ui_Demo2_screen_init(void)
{
    ui_Demo2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Demo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_Demo2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_left_panel_4 = lv_obj_create(ui_Demo2);
    lv_obj_set_width(ui_left_panel_4, 20);
    lv_obj_set_height(ui_left_panel_4, 20);
    lv_obj_clear_flag(ui_left_panel_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_left_panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_left_panel_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_left_panel_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_right_panel_4 = lv_obj_create(ui_Demo2);
    lv_obj_set_width(ui_right_panel_4, 20);
    lv_obj_set_height(ui_right_panel_4, 20);
    lv_obj_set_align(ui_right_panel_4, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_right_panel_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_right_panel_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_right_panel_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_right_panel_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Demo2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -80);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Hello world");

    ui_Chart2 = lv_chart_create(ui_Demo2);
    lv_obj_set_width(ui_Chart2, 150);
    lv_obj_set_height(ui_Chart2, 100);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_BAR);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x22CBB5),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

    lv_obj_add_event_cb(ui_left_panel_4, ui_event_left_panel_4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_right_panel_4, ui_event_right_panel_4, LV_EVENT_ALL, NULL);

}
