// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: display_ball

#include "../ui.h"

void ui_Demo1_screen_init(void)
{
    ui_Demo1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Demo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Demo1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Demo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_left_panel_3 = lv_obj_create(ui_Demo1);
    lv_obj_set_width(ui_left_panel_3, 20);
    lv_obj_set_height(ui_left_panel_3, 20);
    lv_obj_clear_flag(ui_left_panel_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_left_panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_left_panel_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_left_panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_right_panel_3 = lv_obj_create(ui_Demo1);
    lv_obj_set_width(ui_right_panel_3, 20);
    lv_obj_set_height(ui_right_panel_3, 20);
    lv_obj_set_align(ui_right_panel_3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_right_panel_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_right_panel_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_right_panel_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_right_panel_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel1 = lv_colorwheel_create(ui_Demo1, true);
    lv_obj_set_width(ui_Colorwheel1, 150);
    lv_obj_set_height(ui_Colorwheel1, 150);
    lv_obj_set_align(ui_Colorwheel1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_left_panel_3, ui_event_left_panel_3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_right_panel_3, ui_event_right_panel_3, LV_EVENT_ALL, NULL);

}
