// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: display_ball

#include "../ui.h"

void ui_Demo_screen_init(void)
{
    ui_Demo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Demo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Demo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Demo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_left_panel_2 = lv_obj_create(ui_Demo);
    lv_obj_set_width(ui_left_panel_2, 20);
    lv_obj_set_height(ui_left_panel_2, 20);
    lv_obj_clear_flag(ui_left_panel_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_left_panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_left_panel_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_left_panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_right_panel_2 = lv_obj_create(ui_Demo);
    lv_obj_set_width(ui_right_panel_2, 20);
    lv_obj_set_height(ui_right_panel_2, 20);
    lv_obj_set_align(ui_right_panel_2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_right_panel_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_right_panel_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_right_panel_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_right_panel_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Demo, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_add_event_cb(ui_left_panel_2, ui_event_left_panel_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_right_panel_2, ui_event_right_panel_2, LV_EVENT_ALL, NULL);

}
